name: Daniel De Wispelaere
favicon: null
layout_spectrum: 0
typography_spectrum: 1
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Daniel De Wispelaere - Restauratie - Decoratie - Schilder
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#C64B41'
    - '#66635D'
    - '#BCB5A3'
    - '#F1DEC8'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
